import {
    Github,
    Gitlab,
    Code2,
    Terminal,
    PenBox,
    BookOpen,
    FileText,
    Globe,
    Home,
    Link,
    ExternalLink,
    Mail,
    Send,
    Phone,
    MessageCircle,
    AtSign,
    MapPin,
    Youtube,
    Video,
    Music,
    Mic,
    Camera,
    Rss,
    X,
    Linkedin,
    Instagram,
    Facebook,
    Twitch,
    Slack,
    Figma,
    Dribbble,
    Briefcase,
    Bookmark,
    Heart,
    Star,
    Cloud,
    Smartphone,
    type LucideIcon,
} from "lucide-react"
import type { ConnectIconName } from "@/types/site-content"

const ICON_MAP: Record<ConnectIconName, LucideIcon> = {
    Github,
    Gitlab,
    Code2,
    Terminal,
    PenBox,
    BookOpen,
    FileText,
    Globe,
    Home,
    Link,
    ExternalLink,
    Mail,
    Send,
    Phone,
    MessageCircle,
    AtSign,
    MapPin,
    Youtube,
    Video,
    Music,
    Mic,
    Camera,
    Rss,
    X,
    Linkedin,
    Instagram,
    Facebook,
    Twitch,
    Slack,
    Figma,
    Dribbble,
    Briefcase,
    Bookmark,
    Heart,
    Star,
    Cloud,
    Smartphone,
}

const ICON_LABELS: Record<ConnectIconName, string> = {
    Github: "GitHub",
    Gitlab: "GitLab",
    Code2: "コード",
    Terminal: "ターミナル",
    PenBox: "ブログ",
    BookOpen: "ドキュメント",
    FileText: "記事",
    Globe: "ウェブサイト",
    Home: "ホーム",
    Link: "リンク",
    ExternalLink: "外部リンク",
    Mail: "メール",
    Send: "送信",
    Phone: "電話",
    MessageCircle: "メッセージ",
    AtSign: "メンション",
    MapPin: "場所",
    Youtube: "YouTube",
    Video: "動画",
    Music: "音楽",
    Mic: "ポッドキャスト",
    Camera: "写真",
    Rss: "RSS",
    X: "X (Twitter)",
    Linkedin: "LinkedIn",
    Instagram: "Instagram",
    Facebook: "Facebook",
    Twitch: "Twitch",
    Slack: "Slack",
    Figma: "Figma",
    Dribbble: "Dribbble",
    Briefcase: "仕事",
    Bookmark: "ブックマーク",
    Heart: "お気に入り",
    Star: "スター",
    Cloud: "クラウド",
    Smartphone: "アプリ",
}

export function getConnectIcon(name: ConnectIconName): LucideIcon {
    return ICON_MAP[name] ?? ExternalLink
}

export function getConnectIconLabel(name: ConnectIconName): string {
    return ICON_LABELS[name] ?? name
}

export const CONNECT_ICON_OPTIONS: ConnectIconName[] = [
    "Github",
    "Gitlab",
    "Code2",
    "Terminal",
    "PenBox",
    "BookOpen",
    "FileText",
    "Globe",
    "Home",
    "Link",
    "ExternalLink",
    "Mail",
    "Send",
    "Phone",
    "MessageCircle",
    "AtSign",
    "MapPin",
    "Youtube",
    "Video",
    "Music",
    "Mic",
    "Camera",
    "Rss",
    "X",
    "Linkedin",
    "Instagram",
    "Facebook",
    "Twitch",
    "Slack",
    "Figma",
    "Dribbble",
    "Briefcase",
    "Bookmark",
    "Heart",
    "Star",
    "Cloud",
    "Smartphone",
]
